# FoML Assignment 0
> Foundations of Machine Learning CS5590  Assignment 0

- toc: true 
- badges: false
- comments: true
- categories: [Quizzes and assignments - Foundations of Machine Learning ]
- author: Abhishek Kumar Dubey

This homework is intended to review basic pre-requisites in the following topics:
- Linear Algebra, Probability, Python programming

# Practice Questions

The questions below are only for your practice - no submission required. (The exam could include questions from this list though!)<br>

## 1. Numpy


The following questions should be done using numpy operations. Each exercise can be solved with a maximum of 4-5 lines of Python code. Please avoid the use of iterative constructs (such as for loops) to the extent possible, and use matrix/vector operations to achieve the objectives.<br>
Please use https://docs.python.org/3/tutorial/ for any reference required.

(a) Import the numpy package under the name np. Print the numpy version and the configuration.

In [7]:
import numpy as np
print('Version:\n',np.__version__)


Version:
 1.21.5


In [8]:
print('\nconfiguration:\n',np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yasmi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yasmi/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yasmi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yasmi/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yasmi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yasmi/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yasmi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yasmi/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE

(b) Create a null vector of size 10, and output the vector to the terminal.

In [9]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(c) Create a null vector of size 10 but the fifth value which is 1. Output the vector to the terminal.

In [10]:
null_vector = (np.arange(10) == 4).astype(int)
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


(d) Reverse a vector (first element becomes last).

In [13]:
vector=np.array([1,2,3,4,5])
print(vector[::-1])

[5 4 3 2 1]


(e) Create an $n × n$ array with checkerboard pattern of zeros and ones.

In [35]:
n=5
checkerboard = np.ones(shape=(5,5))
checkerboard[::2,::2]=0
checkerboard[1::2,1::2]=0
print(checkerboard)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


(f) Given an $n × n$ array, sort the rows of array according to $m^{th}$ column of array.