# FoML Assignment 0
> Foundations of Machine Learning CS5590  Assignment 0

- toc: true 
- badges: false
- comments: true
- categories: [Quizzes and assignments - Foundations of Machine Learning ]
- author: Abhishek Kumar Dubey

This homework is intended to review basic pre-requisites in the following topics:
- Linear Algebra, Probability, Python programming

# Practice Questions

The questions below are only for your practice - no submission required. (The exam could include questions from this list though!)<br>

## 1. Numpy
---


The following questions should be done using numpy operations. Each exercise can be solved with a maximum of 4-5 lines of Python code. Please avoid the use of iterative constructs (such as for loops) to the extent possible, and use matrix/vector operations to achieve the objectives.<br>
Please use https://docs.python.org/3/tutorial/ for any reference required.

(a) Import the numpy package under the name np. Print the numpy version and the configuration.

In [1]:
import numpy as np
np.set_printoptions(precision=3)
print('Version:\n',np.__version__)
# print('\nconfiguration:\n',np.show_config())


Version:
 1.21.5


(b) Create a null vector of size 10, and output the vector to the terminal.

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(c) Create a null vector of size 10 but the fifth value which is 1. Output the vector to the terminal.

In [3]:
null_vector = (np.arange(10) == 4).astype(int)
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


(d) Reverse a vector (first element becomes last).

In [4]:
vector=np.array([1,2,3,4,5])
print(vector[::-1])

[5 4 3 2 1]


(e) Create an $n × n$ array with checkerboard pattern of zeros and ones.

In [5]:
n=5
checkerboard = np.ones(shape=(5,5))
checkerboard[::2,::2]=0
checkerboard[1::2,1::2]=0
print(checkerboard)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


(f) Given an $n × n$ array, sort the rows of array according to $m^{th}$ column of array.

In [6]:
n=5
m=2 # sort by column
random_array = np.random.randint(1,100,size=(n,n))
print('Original array:\n',random_array)
print('sorted array:\n',random_array[random_array[:,m].argsort()])

Original array:
 [[88 22 64 73 98]
 [ 7 63 33 96 69]
 [22 22 32 79 55]
 [33 18 76 85 44]
 [17 93 71 87 88]]
sorted array:
 [[22 22 32 79 55]
 [ 7 63 33 96 69]
 [88 22 64 73 98]
 [17 93 71 87 88]
 [33 18 76 85 44]]


(g) Create an $n × n$ array with $(i + j)^{th}$-entry equal to $i + j$.

In [7]:
n=5
print(np.add.outer(range(n),range(n)))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


(h) Consider a $\left(6,7,8\right)$ shape array, what is the index $\left(x,y,z\right)$ of the $100^{th}$ element (of the entire structure)?

In [21]:
array = np.arange(0,6*7*8).reshape((6,7,8))
n=100
x = int(n/(7*8))
n=n%(7*8)
y = int(n/(8))
z=n%(8)
print('Answer: (x,y,z) = ({},{},{})'.format(x,y,z))
assert array.flatten()[x*7*8+y*8+z] == array[x,y,z]
# OR
print ('Answer: (x,y,z) = ({},{},{})'.format(*np.unravel_index(100, (6,7,8))))


Answer: (x,y,z) = (1,5,4)
Answer: (x,y,z) = (1,5,4)


(i) Multiply a $5 × 3$ matrix by a $3 × 2$ matrix (real matrix product).

In [9]:
matA = np.random.randint(9,size=(5,3))
matB = np.random.randint(9,size=(3,2))
prod = np.matmul(matA,matB)
print('matA:\n',matA)
print('matB:\n',matB)
print('product:\n',prod)

matA:
 [[3 2 6]
 [6 1 6]
 [8 1 8]
 [4 8 4]
 [5 0 2]]
matB:
 [[3 7]
 [5 4]
 [5 1]]
product:
 [[49 35]
 [53 52]
 [69 68]
 [72 64]
 [25 37]]


(j) Create random vector of size $10$ and replace the maximum value by $0$.

In [10]:
mat = np.random.randint(9,size=10)
print('mat:\n',mat)
mat[mat.argmax()]=0
print('New mat:\n',mat)

mat:
 [7 8 4 3 8 2 0 3 7 0]
New mat:
 [7 0 4 3 8 2 0 3 7 0]


(k) How to find the closest value (to a given scalar) in an array?

In [11]:
mat = np.random.randint(9,size=10)
scalar = 5
print('mat:\n',mat)
closest = mat[np.absolute(mat-scalar).argmin()]
print('closest value to scalar={} is {}'.format(scalar,closest))

mat:
 [4 5 3 7 8 6 3 4 0 4]
closest value to scalar=5 is 5


(l) Subtract the mean of each row from each corresponding row of a matrix.

In [14]:
mat = np.random.randint(9,size=(4,3))
print('mat:\n',mat)
mean = mat.mean(axis=1)
new_mat = mat-mean.T[...,None]
print('After subtracting mean from each row:\n',new_mat)


mat:
 [[8 6 4]
 [5 2 7]
 [5 1 4]
 [8 0 1]]
After subtracting mean from each row:
 [[ 2.     0.    -2.   ]
 [ 0.333 -2.667  2.333]
 [ 1.667 -2.333  0.667]
 [ 5.    -3.    -2.   ]]


(m) Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices - you should consider it only once)?

In [16]:
mat = np.random.randint(9,size=4)
indexes = np.array([0,0,3])
print('mat:\n',mat)
mat[np.unique(indexes)]+=1
print('mat:\n',mat)

mat:
 [4 5 6 7]
mat:
 [5 5 6 8]


(n) How to find the most frequent value in an array?

In [18]:
mat = np.random.randint(3,size=5)
print('mat:\n',mat)
value,count = np.unique(mat,return_counts=True)
print('most frequent value = {}'.format(value[count.argmax()]))

mat:
 [0 2 1 0 0]
most frequent value = 0


(o) Extract all the contiguous $3 × 3$ blocks from a random $10 × 10$ matrix.

In [46]:
mat = np.random.randint(0,9,(10,10))
n=3
i=1+(mat.shape[0]-n)
j=1+(mat.shape[1]-n)
res = np.lib.stride_tricks.as_strided(mat,shape=(i,j,n,n),strides=mat.strides+mat.strides)


(p) Compute the rank, trace and determinant of a matrix.

In [67]:
mat = np.random.randint(0,9,(4,4))
print('Matrix :\n{}'.format(mat))
print('Matrix Rank :{}'.format(np.linalg.matrix_rank(mat)))
print('Matrix Determinant :{:.2f}'.format(np.linalg.det(mat)))

Matrix :
[[2 2 2 0]
 [5 2 5 0]
 [7 3 5 4]
 [8 5 2 1]]
Matrix Rank :4
Matrix Determinant :-132.00


## 2. Linear Algebra
---

(a) Prove or disprove: Empty set is a vector space.


- Answer:<br>[Axioms of  vector spaces:](https://www.math.ucla.edu/~tao/resource/general/121.1.00s/vector_axioms.html)<br>
    - A real vector space is a set $X$ with a special element $0$, and three operations:<br>
        - Addition:  Given two elements $x$, $y$ in $X$, one can form the sum $x+y$, which is also an element of $X$.<br>
        - Inverse: Given an element $x$ in $X$, one can form the inverse $-x$, which is also an element of $X$.<br>
        - Scalar multiplication:  Given an element $x$ in $X$ and a real number $c$, one can form the product $cx$, which is also an element of $X$.<br><br>
    - As Empty set doesn't contain element $0$ Hence we can say that Empty set is __NOT__ a vector space
<br>


(b) Show that the inverse of $M=I+\left({\mathbf{uv}}^T \right)$ is of the type $I+\alpha \left({\mathbf{uv}}^T \right)$, where $\mathit{\mathbf{u}},\mathit{\mathbf{v}}\in {\mathbb{R}}^n ,{\mathit{\mathbf{v}}}^T \mathit{\mathbf{u}}\not= 0$
1. Continuing from previous question, find $\alpha$.
2. For what $u$ and $v$ is $M$ singular?
3. Find the null space of $M$, if it is singular.




- Answer:

(c) <br>
1. Consider the 2 × 2 matrix: 
$A=\left\lbrack \begin{array}{cc}
-2 & 2\\
-6 & 5
\end{array}\right\rbrack$
There exists vectors such that when the matrix $A$ acts on those vectors, the subspace of the vectors does not change. Mathematically, $Ax = \lambda I$.<br> 
The vectors $x$ are called `eigenvectors` and the values $\lambda$ are the corresponding `eigenvalues`. Find the eigenvalues and corresponding eigenvectors for the matrix $A$.<br>
2. Consider a diagonal matrix $\Lambda$ which has the eigenvalues of $A$ as its diagonal entries. Find the matrix $U$ such that the equation $AU = U\Lambda$ holds.
3. Note that we can write the matrix $A$ as $A$ = $U \Lambda U^{−1}$. Find the inverse of the matrix $U$ computed in the previous question and verify.


- Answer:<br><br>
1. <br>$A=\left\lbrack \begin{array}{cc}
-2 & 2\\
-6 & 5
\end{array}\right\rbrack$<br><br>
$\mathrm{Ax}=\lambda x$<br><br>
$\Rightarrow \mathrm{Ax}-\lambda \;x=0\Rightarrow \left(A-\lambda I\right)x=0$<br><br>
$\left\lbrack \begin{array}{cc}
-2 & 2\\
-6 & 5
\end{array}\right\rbrack -\lambda \left\lbrack \begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right\rbrack =0$<br><br>
$\left\lbrack \begin{array}{cc}
-2 & 2\\
-6 & 5
\end{array}\right\rbrack -\left\lbrack \begin{array}{cc}
\lambda  & 0\\
0 & \lambda 
\end{array}\right\rbrack =0$<br><br>
$\left\lbrack \begin{array}{cc}
-2-\lambda  & 2\\
-6 & 5-\lambda 
\end{array}\right\rbrack =0$<br><br>
$\left(-2-\lambda \right)\left(5-\lambda \right)-2\left(-6\right)=0$<br>
$-10+2\lambda -5\lambda_{\;} +\lambda^2 +12=0$<br>
$\lambda^2 -3\lambda +2=0$<br>
$\left(\lambda -2\right)\left(\lambda -1\right)=0$<br>
$\lambda =2,\lambda =1$<br>
for $\lambda =2$ put $\lambda$ value in $\left(A-\lambda I\right)x=0$<br><br>
$\left\lbrack \begin{array}{cc}
-2-\lambda  & 2\\
-6 & 5-\lambda 
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
$\left\lbrack \begin{array}{cc}
-2-2 & 2\\
-6 & 5-2
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
$\left\lbrack \begin{array}{cc}
-4 & 2\\
-6 & 3
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
We get below 2 equations: <br>
$-4x+2y=0$<br>
$-6x+3y=0$<br>
After solving we get :<br><br>
$\left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
1\\
2
\end{array}\right\rbrack$<br><br>
Similarly for $\lambda$=1, we get:<br><br>
$\left\lbrack \begin{array}{cc}
-2-\lambda  & 2\\
-6 & 5-\lambda 
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
$\left\lbrack \begin{array}{cc}
-2-1 & 2\\
-6 & 5-1
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
$\left\lbrack \begin{array}{cc}
-3 & 2\\
-6 & 4
\end{array}\right\rbrack \left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
0\\
0
\end{array}\right\rbrack$<br><br>
$-3x+2y=0$<br>
$-6x+4y=0$<br>
After solving above 2 equations we get:<br><br>
$\left\lbrack \begin{array}{c}
x\\
y
\end{array}\right\rbrack =\left\lbrack \begin{array}{c}
2\\
3
\end{array}\right\rbrack$<br><br>
2. <br> $\mathrm{AU}=U\Lambda$ holds when $U$ is a the matrix with all the eigen vectors.<br>
Hence <br><br>
$U=\left\lbrack \begin{array}{cc}
2 & 1\\
3 & 2
\end{array}\right\rbrack$<br><br>
3. <br>  $A$ = $U \Lambda U^{−1}$<br><br>
$U=\left\lbrack \begin{array}{cc}
2 & 1\\
3 & 2
\end{array}\right\rbrack$<br><br>
$U^{-1} =\frac{1}{|U|}\cdot \mathrm{Adj}\;U$<br><br>
$\Rightarrow U^{-1} =\frac{1}{4-3}\left\lbrack \begin{array}{cc}
2 & -1\\
-3 & 2
\end{array}\right\rbrack$<br><br>
$\Rightarrow U^{-1} =\left\lbrack \begin{array}{cc}
2 & -1\\
-3 & 2
\end{array}\right\rbrack$<br><br>
$U^{\;} \Lambda U^{-1} =\left\lbrack \begin{array}{cc}
2 & 1\\
3 & 2
\end{array}\right\rbrack \left\lbrack \begin{array}{cc}
1 & 0\\
0 & 2
\end{array}\right\rbrack \left\lbrack \begin{array}{cc}
2 & -1\\
-3 & 2
\end{array}\right\rbrack$<br><br>
$\Rightarrow U^{\;} \Lambda U^{-1} =\left\lbrack \begin{array}{cc}
-2 & 2\\
-6 & 5
\end{array}\right\rbrack$<br><br>
Which is ame as $A$, hence proved.


Below is the solution of above question using Numpy, The Eigen Vector seems to be different because it's normalized one.

In [106]:
import numpy as np
m = np.array([[-2, 2],
              [-6, 5]])
eigValue,eigVector = np.linalg.eig(m)
print('eigen Value:\n',eigValue)
print('eigen Vector:\n',eigVector)

eigen Value:
 [1. 2.]
eigen Vector:
 [[-0.555 -0.447]
 [-0.832 -0.894]]


In [105]:
U = np.array([[2, 1],
              [3, 2]])
Lambda  = np.array([[1, 0],
                    [0, 2]])
U_inv = np.linalg.inv(U)

print(U.dot(Lambda).dot(U_inv))

[[-2.  2.]
 [-6.  5.]]


(c) Show that for any square matrix $A$, the eigenvectors of $A$ are also eigenvectors of $A^2$. What are the eigenvalues for $A^2$?